name: SharesPlugin
developer: kasteelheertje
main: economy.pack.Main
version: 1.0
commands:
    economy:
        description: Modify the balances of every player!
        usage: /economy
        
    bal:
        description: Shows your current balance!
        usage: /bal
        
    worth:
        description: Shows the current stock!
        usage: /worth

    
    
    