name: SharesPlugin
developer: kasteelheertje
main: economy.pack.Main
version: 1.0

commands:
  economy:
    description: Modify the balances of every player!
  balance:
    aliases:
    - bal
    description: Shows your current balance!
  stocks:
    description: Shows the current stocks!
    
    
    